locals {
  domain = "${var.subdomain}.${var.parent_domain}"
}
resource "github_repository" "main" {
  name = var.github_repo_name
  homepage_url = local.domain
  license_template = "GPL-3.0"
}

resource "github_repository_file" "readme-terraform" {
  repository = github_repository.main.name
  depends_on = [ github_repository.main ]
  file = "README-terraform.md"
  content = <<EOF
Static site and Github repo managed by Evan's Opentofu (Terraform) infrastructure.

* This repository's `.tf` files: https://github.com/erosson/infra/tree/main/tf/${local.domain}
* Public site: https://${local.domain}
* Backend site: https://${var.cloudflare_pages_name}.pages.dev
* Deployment status: https://dash.cloudflare.com/${var.account_id}/pages/view/${var.cloudflare_pages_name}

_This file is autogenerated, don't edit_
EOF
}

resource "github_repository_file" "index-html" {
  repository = github_repository.main.name
  # depends-on the project makes pushing this file trigger our first deployment
  depends_on = [ github_repository.main, cloudflare_pages_project.main ]
  file = "index.html"
  content = <<EOF
<!doctype html>
<html>
<body>
hello, tf-generated-index!
</body>
</html>
EOF
}

resource "cloudflare_pages_project" "main" {
  name = var.cloudflare_pages_name
  production_branch = "main"
  account_id = var.account_id
  build_config {
    build_command = "true"
    destination_dir = "."
  }
  source {
    type = "github"
    config {
      owner = "erosson"
      repo_name = var.github_repo_name
      production_branch = "main"
    }
  }
  depends_on = [ github_repository.main ]
}

resource "cloudflare_pages_domain" "main" {
  account_id   = var.account_id
  project_name = var.cloudflare_pages_name
  domain       = local.domain
  depends_on = [cloudflare_pages_project.main]
}

resource "cloudflare_record" "main" {
  zone_id = var.zone_id
  type = "CNAME"
  name = var.github_repo_name
  value = "${cloudflare_pages_project.main.name}.pages.dev."
  depends_on = [cloudflare_pages_domain.main]
}