#!/bin/bash
set -eu
cd "`dirname "$0"`"

# image name below should match the one in droplet-setup.sh
scp -i .ssh/id_rsa docker-compose.yml root@static-droplet.erosson.org:/root/docker-compose.yml
cat <<EOF | ./ssh
docker compose pull
docker compose down
docker compose up -d
EOF