#!/bin/bash
set -eux
cd "`dirname "$0"`"

if [ -v CI ]; then
    mkdir -p .ssh
    echo "$STATIC_SITES_DEPLOY_PUBLIC_KEY" > .ssh/id_rsa.pub
    echo "$STATIC_SITES_DEPLOY_PRIVATE_KEY" > .ssh/id_rsa
    chmod 600 .ssh/id_rsa
fi
# image name below should match the one in droplet-setup.sh
#
# no need for `docker compose down` below! `up` will restart only changed images:
# https://www.reddit.com/r/selfhosted/comments/17of3lt/what_is_the_best_way_to_update_a_docker_image/
# scp -i .ssh/id_rsa -o UserKnownHostsFile=.ssh/known_hosts docker-compose.yml root@static-droplet.erosson.org:/root/docker-compose.yml
# TODO: this is not secure, but I gave up fiddling with known_hosts via terraform
scp -i .ssh/id_rsa  -o StrictHostKeyChecking=no server/docker-compose.yml root@static-droplet.erosson.org:/root/docker-compose.tmp.yml
scp -i .ssh/id_rsa  -o StrictHostKeyChecking=no -p server/droplet-setup.sh root@static-droplet.erosson.org:/root/droplet-setup.sh
./ssh ./droplet-setup.sh