#!/bin/bash
set -eu
cd "`dirname "$0"`"

# create ssh auth files, if running in CI. https://stackoverflow.com/a/16946761
if [ -v CI ]; then
    mkdir -p .ssh
    echo "$STATIC_SITES_DEPLOY_PUBLIC_KEY" > .ssh/id_rsa.pub
    echo "$STATIC_SITES_DEPLOY_PRIVATE_KEY" > .ssh/id_rsa
    echo "$STATIC_SITES_DEPLOY_HOST_KEY" > .ssh/known_hosts
fi
# ssh-keygen -f "/home/node/.ssh/known_hosts" -R "static-droplet.erosson.org"
ssh -i .ssh/id_rsa -o UserKnownHostsFile=.ssh/known_hosts root@static-droplet.erosson.org "$@"
# ssh -i .ssh/id_rsa root@www.erosson.org "$@"