#!/bin/bash
set -eu
cd "`dirname "$0"`"

# create ssh auth files, if running in CI. https://stackoverflow.com/a/16946761
if [ -v CI ]; then
    mkdir -p .ssh
    echo "$STATIC_SITES_DEPLOY_PUBLIC_KEY" > .ssh/id_rsa.pub
    echo "$STATIC_SITES_DEPLOY_PRIVATE_KEY" > .ssh/id_rsa
fi
# ssh-keygen -f "/home/node/.ssh/known_hosts" -R "static-droplet.erosson.org"
# ssh -i .ssh/id_rsa -o UserKnownHostsFile=.ssh/known_hosts root@static-droplet.erosson.org "$@"
# TODO: this is not secure, but I gave up fiddling with known_hosts via terraform
ssh -i .ssh/id_rsa -o StrictHostKeyChecking=no root@static-droplet.erosson.org "$@"