locals {
  domain = "${var.subdomain}.${var.domain_name}"
  domain_slug = replace(local.domain, ".", "-")
  # github_repo_name = var.github_repo_name != null ? var.github_repo_name : local.domain
  github_repo_name = var.github_repository.name
  github_owner = replace(var.github_repository.full_name, "/\\/.*$/", "")
  netlify_name = var.netlify_name != null ? var.netlify_name : local.domain_slug
  netlify_url = "${local.netlify_name}.netlify.app"
}

resource "github_repository_file" "readme-terraform" {
  # repository = github_repository.main.name
  repository = local.github_repo_name
  depends_on = [ var.github_repository ]
  file = "README-tf-netlify.md"
  content = <<EOF
Static site and Github repo managed by Evan's Opentofu (Terraform) infrastructure.

* This repository's `.tf` configuration: https://github.com/erosson/infra/tree/main/tf/
* Public site: https://${local.domain}
* Backend site: https://${local.netlify_url}
* Deployment status: TODO

_This file is autogenerated, don't edit_
EOF
}
# * Deployment status: https://app.netlify.com/sites/${local.netlify_name}

resource "netlify_deploy_key" "main" {}

resource "netlify_site" "main" {
  name = local.netlify_name
  custom_domain = local.domain

  repo {
    provider = "github"
    repo_path = var.github_repository.full_name
    repo_branch = "main"
    command = var.repo.command
    dir = var.repo.dir
    deploy_key_id = netlify_deploy_key.main.id
  }
}

resource "cloudflare_record" "main" {
  zone_id = var.domain_cloudflare_zone_id
  type = "CNAME"
  name = var.subdomain
  value = "${local.netlify_url}."
  depends_on = [netlify_site.main]
}