#!/bin/bash
set -eu
cd "$(dirname "$0")"
usage() {
    echo "$@"
    echo "overwrites local git branch BRANCH_NAME with a single commit containing the contents of DIRECTORY."
    echo "usage: $0 DIRECTORY [BRANCH_NAME] [COMMIT_MESSAGE]"
    exit 1
}

[ "$#" == "1" ] || [ "$#" == "2" ] || [ "$#" == "3" ] || usage
DIST="$1"
RELEASE_BRANCH="${2:-$(git branch --show-current).release}"
COMMIT_MSG="${3:-release of branch $(git branch --show-current)}"
[ -d "$DIST" ] || (usage "not a directory: $DIST")
[ "" != "$RELEASE_BRANCH" ] || (usage "must be nonempty: $RELEASE_BRANCH")
[ "" != "$COMMIT_MSG" ] || (usage "must be nonempty: $COMMIT_MESSAGE")
echo DIST="$DIST" RELEASE_BRANCH="$RELEASE_BRANCH" COMMIT_MSG="$COMMIT_MSG"

# the process:
# - init an empty temporary git repository
# - commit the released files to the new repo
# - (force-)push the temp repo back to the main repository's release branch
SELF="$(pwd)"
TMPGIT="$(mktemp -d)"
set -x
git init "$TMPGIT"

# subtrees are one way to do this, but I don't understand it as well.
# An empty repo takes more lines - but it's easier to understand, and we don't
# have to figure out how to clear the release branch's history
#git subtree push --no-verify --prefix="$DIST"

cp -a "$DIST/." "$TMPGIT"
cd "$TMPGIT"
git status
git checkout --orphan main
git add -A
git commit -m "$COMMIT_MSG"

git push --no-verify -f "$SELF" main:"$RELEASE_BRANCH"
cd "$SELF"
rm -rf "$TMPGIT"

git log "$RELEASE_BRANCH"
git ls-tree -r --name-only "$RELEASE_BRANCH"